github: [{username}]
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
issuehunt: # Replace with a single IssueHunt username
ko_fi: # Replace with a single ko_fi username
liberapay: # Replace with a single Liberapay username
open_collective: # Replace with a single open_collective username
patreon: # Replace with a single Patreon username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
polar: # Replace with a single polar username
buy_me_a_coffee: # Replace with a single buy_me_a_coffee username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
