name: Bug report
description: Create a report to help us improve AutoWall.
labels: bug
title: "[BUG REPORT] - "

body:
  - type: markdown
    attributes:
      value: |
        **Please describe your issue clearly and concisely.**

  - type: textarea
    attributes:
      label: Description
      description: A brief description of the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. [First step]
        2. [Second step]
        3. [And so on...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Please provide your Windows version.
      options:
        - Windows 11
        - Windows 10
        - Windows 8
        - Windows 7
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: I performed a [search of the issue tracker](https://github.com/AutoWall/AutoWall/issues?q=is%3Aissue) to avoid opening a duplicate issue.
          required: true
        - label: I understand that not filling out this template correctly may lead to the issue being closed.
          required: true